### ISSUE TITLE
Registrator

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [SciML/ReservoirComputing.jl#1]
@JuliaRegistrator register()

**Comment by MartinuzziFrancesco** [comment]
@JuliaRegistrator register()

**Comment by MartinuzziFrancesco** [comment]
@JuliaRegistrator register()

**Comment by MartinuzziFrancesco** [comment]
@JuliaRegistrator register()

**Comment by MartinuzziFrancesco** [comment]
@JuliaRegistrator register()

**Comment by MartinuzziFrancesco** [comment]
@JuliaRegistrator register()

**Comment by MartinuzziFrancesco** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by MartinuzziFrancesco** [comment]
@JuliaRegistrator register()

**Comment by MartinuzziFrancesco** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
