### ISSUE TITLE
Suggestion for figures: express time axis in Lyapunov time

### ISSUE THREAD

**Issue by Datseris** [SciML/ReservoirComputing.jl#105]
Hey, awesome to see this in Julia! I remember first learning about this methods in a 2018/2019 meeting where Ed Ott presented their reservoir computing work for chaotic timeseries prediction, and we presented the work based on [TimeseriesPrediction.jl](https://github.com/JuliaDynamics/TimeseriesPrediction.jl), (now published here https://link.springer.com/article/10.1007/s00332-019-09588-7 )

In chaotic timeseries prediction it is customary to express the time axis in units of the Lyapunov time, `1/λ` with `λ` the Maximum Lyapunov exponent. For many famous systems (e.g. Lorenz63) you can find its value online, or use the `lyapunov` function from DynamicalSystems.jl, https://juliadynamics.github.io/DynamicalSystems.jl/dev/chaos/lyapunovs/

**Comment by MartinuzziFrancesco** [comment]
addressed in #113
