### ISSUE TITLE
Division by zero in init_reservoir_givendeg()

### ISSUE THREAD

**Issue by AnHeuermann** [SciML/ReservoirComputing.jl#109]
When using `init_reservoir_givendeg` for small `res_size` in combination with a low `degree` it is possible to devide by zero.

In [init_reservoir_givendeg](https://github.com/SciML/ReservoirComputing.jl/blob/master/src/esn_reservoirs.jl#L7-L18) `rho_w` can be zero if all eigenvalues of `W` are zero.
```julia
rho_w = maximum(abs.(eigvals(W)))
```
In that case `init_reservoir_givendeg` will return a `W` containing `NaN` or `±Inf`.

My suggestion:
Add an error if `rho_w` is zero or generate `W` until `rho_w` is not zero any more.

The same issue is true for `init_reservoir_givensp`.

**Comment by MartinuzziFrancesco** [comment]
Thanks for noticing this, I will add an error message to both functions

**Comment by MartinuzziFrancesco** [comment]
added in #113
