### ISSUE TITLE
Can not run examples code

### ISSUE THREAD

**Issue by abrari-itk** [SciML/ReservoirComputing.jl#110]
Dear ReservoirComputing developer
I tried to run the Lorenz test case like in README.md, but I face an issue. I exactly just copied and paste the code, without any modification, however, the code shows an error namely during line nla_type = NLAT2(),  it can not recognize NLAT2(). Attached is the exact screenshot of the error message. 

![image](https://user-images.githubusercontent.com/94313669/141692892-d6cab68b-3845-4492-b657-ed60d9637fbc.png)

I hope that you can help me what should I do to resolve this error? I tried to change the nla_type with NLADefault() but it still show a similar error like the screenshot
Regards
Abrari

**Comment by MartinuzziFrancesco** [comment]
this is strange, both methods are exported. Could you post the code you are running just to be sure? What version of ReservoirComputing are you running?

**Comment by abrari-itk** [comment]
Thanks for responding
I have just installed it today by using Pkg.add("ReservoirComputing"), so I expect that it should give me the latest version. 
Below are the code that I run: 

using ParameterizedFunctions
using OrdinaryDiffEq
using ReservoirComputing

#lorenz system parameters
u0 = [1.0,0.0,0.0]                       
tspan = (0.0,200.0)                      
p = [10.0,28.0,8/3]
#define lorenz system
function lorenz(du,u,p,t)
    du[1] = p[1]*(u[2]-u[1])
    du[2] = u[1]*(p[2]-u[3]) - u[2]
    du[3] = u[1]*u[2] - p[3]*u[3]
end

#solve and take data
prob = ODEProblem(lorenz, u0, tspan, p)  
sol = solve(prob, ABM54(), dt=0.02)   
v = sol.u
data = Matrix(hcat(v...))
shift = 300
train_len = 5000
predict_len = 1250
train = data[:, shift:shift+train_len-1]
test = data[:, shift+train_len:shift+train_len+predict_len-1]

approx_res_size = 300
radius = 1.2
degree = 6
activation = tanh
sigma = 0.1
beta = 0.0
alpha = 1.0
nla_type = NLAT2()
extended_states = false

esn = ESN(approx_res_size,
    train,
    degree,
    radius,
    activation = activation, #default = tanh
    alpha = alpha, #default = 1.0
    sigma = sigma, #default = 0.1
    nla_type = nla_type, #default = NLADefault()
    extended_states = extended_states #default = false
    )

**Comment by abrari-itk** [comment]
Hi, after checking again, I think the installed version is ReservoirComputing v0.5.0

**Comment by MartinuzziFrancesco** [comment]
Current version is 0.7.0, switching to that should solve the issue. I've run the example with it and it seems to be working on my machine

**Comment by MartinuzziFrancesco** [comment]
v0.5.0 didn't have the ```NonLinearAlgorithm```  types, they were added in 0.6.0

**Comment by abrari-itk** [comment]
Thanks for your guide, now it works perfectly.

**Comment by MartinuzziFrancesco** [comment]
Always happy to help!
