### ISSUE TITLE
Incorporating prior knowledge into ESNs using hybrid ESN

### ISSUE THREAD

**Issue by AnasAbdelR** [SciML/ReservoirComputing.jl#74]
Hi,

This paper demonstrates how prior knowledge of the dynamics can be incorporated into the ESN architecture:
https://arxiv.org/pdf/1803.04779.pdf

It had some interesting results produced in the paper below using a reduced order model of a physical process:
https://arxiv.org/pdf/2001.04027.pdf

The basic idea is that instead of having dims = (D_r, M) as an input weight matrix into the reservoir (where D_r is the dimension of the reservoir and M is the dimension of the states) , you have (D_r, M+K) where K is the output dimension of the prior knowledge model. The initialisation of the input weight connections are configured such that some γ of the reservoir nodes are connected to the raw inputs, and the rest are connected to the prior knowledge model. The same is also done for the output read out. 

They use a Erdos-Renyi network for the reservoir, and an additional modification to the reservoir states outputs that empirically helped their situation, but I don't think that will be needed for the general case.

**Comment by AnasAbdelR** [comment]
ESN's with different layers according to the example in the docs looks like this:

```julia
W = DLR(approx_res_size, r)
W_in = init_dense_input_layer(approx_res_size, size(train, 1), sigma)

esndlr = ESN(W,
    train,
    W_in,
    activation = activation,
    alpha = alpha,
    nla_type = nla_type,
    extended_states = extended_states)

W_out = ESNtrain(esndlr, beta)
output = ESNpredict(esndlr, predict_len, W_out)

```
Maintaining the spirit of this workflow, the implementation for this paper should follow a similar style. For the first bit i.e input weights and states of the reservoir, a normal ESN implementation is such that:

![CodeCogsEqn (4)](https://user-images.githubusercontent.com/73660335/98311626-d6dbfd00-1f9d-11eb-931f-bb0e34e89d02.png)

where equation for evolving reservoir states is: r(t+dt) = tanh(W * x(t) + W_in * u(t))
W : dims(r, r) where r is the # of reservoir nodes
x(t) : dims(r, t) where t is the number of time steps
W_in : dims(r, u) where u is the dimensions of the input states
u(t) : dims(u, t)

According to the HESN paper, W_in is such that:

1.  The matrix W_in is to have exactly one nonzero element in each row
2.  The nonzero elements are independently chosen from the uniform distribution on the interval [−σ, σ]
3.  These nonzero elements are randomly chosen such that a fraction γ of the reservoir nodes are connected exclusively to the raw input u(t) and the remaining fraction are connected exclusively to the the output of the model based predictor K[u(t)]

Therefore the HESN W_in and evolved reservoir states is such that:

![CodeCogsEqn (5)](https://user-images.githubusercontent.com/73660335/98312003-c5472500-1f9e-11eb-93e8-5cada858daa7.png)

Where we now have: 
r(t+dt) = tanh(W* x(t) + **W_in** * **u(t)**)
**W_in** : dims(r, u+k) where k is the number of inputs from the prior model
**u(t)** : dims(u+k, t)

This means if the user provides the states of their data, and the values of their prior model in that order, all we would need to do in the back is create the W_in as instructed. This has already been implemented in this PR #76 

Next up is the training implementation,  to get W_out and the prediction implementation

**Comment by AnasAbdelR** [comment]
For a normal ESN, the implementation in ReservoirComputing.jl for state generation using a leaky fixed RNN is:

```julia
function leaky_fixed_rnn(activation, alpha, W, W_in, x, y)
    return (1-alpha).*x + alpha*activation.((W*x)+(W_in*y))
end
```
Where y is the training data, x is the reservoir states and W are the weights of the reservoir. At first glance, since it was assumed earlier that the user provides training data with the prior model outputs along with the states  we get: dims(u+k, t). Since also W_in is generated according to the HESN framework , it should be: dims(r, k+t) so that:

```julia
W_in*y = dims(r, k+u)*dims(k+u, t) = dims(r, t) #  the exact dimension of W*x
```
Therefore it appears that there shouldn't be a need for any changes in implementation for generating the states without considering the extended_states implementation for simplicity.

With regards to prediction for a normal ESN it is implemented in ReservoirComputing.jl as:

```julia
function ESNpredict(esn::AbstractLeakyESN,
    predict_len::Int,
    W_out::AbstractArray{Float64})

    output = zeros(Float64, esn.in_size, predict_len)
    x = esn.states[:, end]

    for i=1:predict_len
          x_new = nla(esn.nla_type, x)
          out = (W_out*x_new)
          output[:, i] = out
          x = leaky_fixed_rnn(esn.activation, esn.alpha, esn.W, esn.W_in, x, out)
    end
    return output
end
```

Where W_out is dims(u, r), u is the number of raw states being predicted for, and r is the number of reservoir nodes as mentioned above.

Since the paper also includes the prior model into the output, describing it as "_the training can be thought of as optimally deciding on how to weight the information from the knowledge-based and reservoir components_" - the expected dimensions of W_out in this case should be (u, r+k). Assuming we solve for W_out so that it has these dimensions (still need to work it out) the changes of the implementation for prediction should be pretty simple:

```julia
function ESNpredict(esn::AbstractLeakyESN,
    predict_len::Int,
    prior_data::AbstractArray{Float64}
    W_out::AbstractArray{Float64})

    output = zeros(Float64, esn.in_size, predict_len)
    x = esn.states[:, end]
    prior_size = size(prior_model_data, 1)

    for i=1:predict_len
          if i == 1
              x_new = nla(esn.nla_type, x)
              x_new = hcat(x_new, prior_data[:, i]) 
              out = (W_out*x_new)
              output[:, i] = out
              out = hcat(out, prior_data[:, i]) 
              x = leaky_fixed_rnn(esn.activation, esn.alpha, esn.W, esn.W_in, x, out)
          else
              x_new = nla(esn.nla_type, x[1:end-prior_size,:])
              x_new = hcat(x_new, prior_data[:, i])
              out = (W_out*x_new)
              output[:, i] = out
              out = hcat(out, prior_data[:, i]) 
              x = leaky_fixed_rnn(esn.activation, esn.alpha, esn.W, esn.W_in, x, out)
          end
              
    end
    return output
end
```

This way, the output of the HESN  which includes the prior model as per the framework can be seen as tacking its state to the reservoir, and the whole output can be looped back into the input with the right dimensions (i.e including the prior knowledge needed for the W_in) 

@ChrisRackauckas , @MartinuzziFrancesco  let me know what you guys think so far

To-do:
1. Training HESN

**Comment by ChrisRackauckas** [comment]
I thought the Hybrid ESN needed to act like a filter so it essentially needs to act as a function within the loop?

**Comment by AnasAbdelR** [comment]
That's what I thought as well - in the original paper they mention it as k[u(t)] - but they don't clarify if what they mean is use the model as filter, or integrate it and incorporate its values, however in the other paper that uses their implementation (Learning ergodic averages in chaotic systems), they do mention this: "the ROM is obtained by integrating the same equations" so I thought it was the latter

**Comment by AnasAbdelR** [comment]
With this implementation though, the model is incorporated into the loop except rather than evaluating the model inside and using it, we just accept a vector of integrated prior model data. 

```julia
function ESNpredict(esn::AbstractLeakyESN,
    predict_len::Int,
    prior_data::AbstractArray{Float64}
    W_out::AbstractArray{Float64})

    output = zeros(Float64, esn.in_size, predict_len)
    x = esn.states[:, end]
    prior_size = size(prior_model_data, 1)

    for i=1:predict_len
          if i == 1
              x_new = nla(esn.nla_type, x) 
              x_new = hcat(x_new, prior_data[:, i]) #<-- append states of prior model at current tstep
              out = (W_out*x_new) #<-- prediction w/ reservoir state & prior model values given solved W_out
              output[:, i] = out
              out = hcat(out, prior_data[:, i]) #<-- append states of prior model for input of next prediction
              x = leaky_fixed_rnn(esn.activation, esn.alpha, esn.W, esn.W_in, x, out)
          else
              x_new = nla(esn.nla_type, x[1:end-prior_size,:])
              x_new = hcat(x_new, prior_data[:, i])
              out = (W_out*x_new)
              output[:, i] = out
              out = hcat(out, prior_data[:, i]) 
              x = leaky_fixed_rnn(esn.activation, esn.alpha, esn.W, esn.W_in, x, out)
          end
              
    end
    return output
end
```

**Comment by AnasAbdelR** [comment]
So here's the workflow implementation of the HESN where the model is provided, and its results:
```julia
using ReservoirComputing, DifferentialEquations, MLJLinearModels

u0 = [1.0,0.0,0.0]                       
tspan = (0.0,1000.0)  
datasize = 100000
tsteps = range(tspan[1], tspan[2], length = datasize)                   

function lorenz(du,u,p,t)
    p = [10.0,28.0,8/3]
    du[1] = p[1]*(u[2]-u[1])
    du[2] = u[1]*(p[2]-u[3]) - u[2]
    du[3] = u[1]*u[2] - p[3]*u[3]
end

function prior_model_data_generator(u0, tspan, tsteps, model = lorenz)
    prob = ODEProblem(lorenz, u0, tspan) 
    sol = Array(solve(prob, saveat = tsteps))
    return sol
end


ode_prob = ODEProblem(lorenz, u0, tspan)
ode_sol = solve(ode_prob, saveat = tsteps)
ode_data =Array(ode_sol)

train_len = 70000

train = ode_data[:, 1:train_len]

test = ode_data[:, train_len+1:end][:, 1:1000]

predict_len = size(test, 2)

tspan_train = (tspan[1], ode_sol.t[train_len])

approx_res_size = 300
radius = 1.2
activation = tanh
degree = 6
sigma = 0.1
beta = 0.3
alpha = 1.0
nla_type = NLADefault()
in_size = 6
out_size = 3
γ = 0.5
prior_model_size = 3
extended_states = false


W_in = physics_informed_input(approx_res_size, in_size, sigma, γ, prior_model_size)
W = ReservoirComputing.init_reservoir_givendeg(approx_res_size, radius, degree)


hesn = HESN(W,
    train,
    prior_model_data_generator,
    u0,
    tspan_train,
    train_len,
    W_in,
    activation = activation,
    alpha = alpha,
    nla_type = nla_type,
    extended_states = extended_states)


linear_model = Ridge(beta, Analytical())
W_out = HESNtrain(linear_model, hesn)

prediction = HESNpredict(hesn,
    predict_len,
    W_out)


plot(transpose(prediction),layout=(3,1), label="predicted")
plot!(transpose(test),layout=(3,1), label="actual")
```

![Example](https://user-images.githubusercontent.com/73660335/98481037-b8584a80-21c5-11eb-9461-6bf6b669bcd5.png)


@ChrisRackauckas @MartinuzziFrancesco what do you think about the user's perspective given this workflow, anything to change?

**Comment by MartinuzziFrancesco** [comment]
I'd say it's in line with all the previous work done on the package and the workflow is similar to other models. It does seem from the paper that they are integrating and incorporating the values, although they are pretty dense with the explanations. Probably we could move prior_model_data_generator inside the HESN construction, giving also the opportunity to the user to choose a solver for the ODEProblem. What do you think about it?

**Comment by AnasAbdelR** [comment]
So instead of taking the function, take the problem that they set up, and just remake it for different time spans when we do prediction?

**Comment by ChrisRackauckas** [comment]
For discrete, taking a function is a bit more general.

**Comment by ChrisRackauckas** [comment]
Hybrid ESN needs docs.

**Comment by AnasAbdelR** [comment]
Going to make this the next PR very soon

**Comment by Vikas-Yadavji** [comment]
Hello, 
I was reading about Hybrid Echo State Network (the papers mentioned above) and stumbled upon this repository. I was going through the codes to understand the implementation. But since I am completely new to Julia, I have to run some codes to understand them. I am facing one issue as of now, if you guys could help me out with it, I will be grateful.

1. Using the above-mentioned workflow, I started running the code step by step. The first problem started when I tried using 'physics_informed_input', it showed the following error:
**ERROR: UndefVarError: physics_informed_input not defined**
Probably 'Using ReservoirComputing' did not include this function, so I included them manually by running include("esn_input_layers.jl")
So now 'physics_informed_input' works fine. 

2. I again faced a similar error with HESN, did the same thing and manually included 'include("hesn.jl")'. But now some different error shows which I am unable to debug
**ERROR: TypeError: in keyword argument nla_type, expected NonLinearAlgorithm, got a value of type NLADefault{Float64}**

I tried a lot but couldn't understand how to fix it. Let me you if you could help me in any way.
Thanks

Best,
Vikas

**Comment by MartinuzziFrancesco** [comment]
Hi Vikas, this is strange since the example provided by Anas above works well on my machine with Julia 1.5.3 and ReservoirComputing 0.6.1. If you are using the same versions my guess would be that something went wrong in the installation of the package. Did you follow the installation instructions in the readme? If so, have you tried calling any other ReservoirComputing function to see if the problem is just with the ones that you mentioned?

**Comment by vikasyadav-py** [comment]
Hello Martinuzzi,
Thank you for reaching out so soon. I am using Ubuntu 20.04 and previously installed Julia 1.5.2. After reading your comment, I reinstalled Julia version 1.5.3. I followed the installation procedure as described in Readme file. I was also able to run the Echo State Network example without any error. But the problem exists when trying to manually include **nla.jl** function.
It still shows the following error when trying to include **nla.jl**
**ERROR: LoadError: cannot assign a value to variable ReservoirComputing.NLADefault from module Main**
 and therefore the following error when calling the **HESN** function
**ERROR: TypeError: in keyword argument nla_type, expected NonLinearAlgorithm, got a value of type NLADefault{Float64}**
I am also attaching the images for better understanding. Please let me know if ou think there is some mistake from my side. Thank you once again.
![image](https://drive.google.com/uc?export=view&id=18mvCZM5AenF-KPARgZkwi1Z7emSYgmi2)
![image](https://drive.google.com/uc?export=view&id=1QNJVzJl6-bnWRTfyryyOiUNKCvBTCHge)

**Comment by MartinuzziFrancesco** [comment]
It's weird, if you are calling ```using ReservoirComputing``` you shouldn't need to ```include``` anything since both HESN and nla functions are already exported. Could you include a script that gives these errors? I'm trying to reproduce them using the script above but it runs fine, even line by line on the REPL

**Comment by vikasyadav-py** [comment]
Yes, even I thought the same, `using ReservoirComputing` should work fine. It does work for the **Echo State Network** example in the readme file but somehow it is creating a problem for the **HESN** case
The script I am using is the same as shown by Anas in the above discussion. I'll explain the installation steps so that there is more clarity.
> 1. In the terminal, I started the Julia environment
> 2. Used the following code for trying the `ESN` example
```Julia
using Pkg
Pkg.add("ReservoirComputing")
Pkg.add("ParameterizedEquations")
Pkg.add("OrdinaryDiffEq")
Pkg.add("Plots)

using ReservoirComputing
using ParameterizedEquations
using OrdinaryDiffEq
using Plots
.
.
.
and so on
```
> This worked fine and I was able to generate the plots as well
> 3. Next, I tried using the `HESN` model, the script as follows
```Julia
using Pkg
Pkg.add("ReservoirComputing")
Pkg.add("DifferentialEquations")
Pkg.add("MLJLinearModels")
Pkg.add("ParameterizedEquations")
Pkg.add("OrdinaryDiffEq")
Pkg.add("Plots)

using ReservoirComputing, DifferentialEquations, MLJLinearModels
using Plots, OrdinaryDiffEq, ParameterizedEquations

u0 = [1.0,0.0,0.0]                       
tspan = (0.0,1000.0)  
datasize = 100000
.
.
.
and so on
```
> Until I faced my first error when using the `physics_informed_input` function
<span style="color:red">ERROR: UndefVarError: physics_informed_input not defined text</span>

**Comment by vikasyadav-py** [comment]
Hello Matinuzzi, 
I edited the previous comment. I just realized that I had not written the script correctly.

**Comment by MartinuzziFrancesco** [comment]
Have you tried calling ```ReservoirComputing.physics_informed_input``` ? I'm still trying to reproduce the errors on my end but with no luck so far

**Comment by vikasyadav-py** [comment]
Yes, tried that as well. `physics_informed_input` method is not present in ReservoirComputing, neither is HESN. It is as if, the package that is being downloaded using `Pkg.add('ReservoirComputing')` doesn't include hesn. Attaching images for reference.

![image](https://drive.google.com/uc?export=view&id=1eAWdw-bDucD0nO5a2x8Nek_vdcvSD2lu)
![image](https://drive.google.com/uc?export=view&id=1lDldyoa7eQweDciB-PqWEnDwFcr4o9P1)

**Comment by MartinuzziFrancesco** [comment]
Ah I see, after adding the HESN we didn't release a new version! I didn't notice it since I was ```dev```ving the repo apparently. I created a registrator pr, as soon as it merges it will suffice to do a ```Pkg.update()``` and the HESN should be present in ReservoirComputing. Sorry it took me so long to figure out a simple oversight

**Comment by vikasyadav-py** [comment]
Ah Ok, all clear. Thank you so much for the effort.

**Comment by MartinuzziFrancesco** [comment]
documentation and tests added in #113
