### ISSUE TITLE
SVESM example error with data_prep function

### ISSUE THREAD

**Issue by rylanperumal** [SciML/ReservoirComputing.jl#95]
I've been working through the svesm_svm_noisytraintest.jl example. I get an error when trying to run the data_prep function. All of the code I have executed are copy pasted from the example provided.

MethodError: no method matching embed(::Dataset{1,Float64}, ::Int64, ::Int64)
Closest candidates are:
  embed(::AbstractArray{T,1}, ::Any, ::Any) where T at 
.julia/packages/DelayEmbeddings/4VbBx/src/embeddings.jl:116
  embed(::AbstractArray{T,1}, ::Any, ::Any, ::H) where {T, H} at 
.julia/packages/DelayEmbeddings/4VbBx/src/embeddings.jl:116

Stacktrace:
 [1] data_prep(::Array{Float64,2}, ::Int64, ::Int64, ::Int64, ::Int64) at ./In[52]:3
 [2] top-level scope at In[59]:2
 [3] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091

**Comment by MartinuzziFrancesco** [comment]
I have updated all SVESM examples since they were not updated to the latest release. They are a little hacky for the moment, but with the next big release the examples folder will be deleted and all examples will be included in the documentation.
